import pandas as pd

df_jan2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/jan2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_feb2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/feb2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_mar2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/mar2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_apr2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/apr2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_may2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/may2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_june2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/june2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_july2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/july2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_aug2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/aug2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_sep2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/sep2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_oct2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/oct2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_nov2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/nov2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})
df_dec2019 = pd.read_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/dec2019.csv', low_memory=False, dtype={'CRSDepTime': 'object', 'CRSArrTime': 'object'})

df_jan2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)

df_feb2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)

df_mar2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)

df_apr2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)

df_may2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)

df_june2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_july2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_aug2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_sep2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_oct2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_nov2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


df_dec2019.rename(columns={'YEAR': 'Year', 'QUARTER': 'Quarter', 'MONTH': 'Month', 'DAY_OF_MONTH': 'DayofMonth', 'DAY_OF_WEEK': 'DayOfWeek', 'FL_DATE': 'FlightDate', 'OP_UNIQUE_CARRIER': 'Reporting_Airline', \
    'OP_CARRIER_AIRLINE_ID': 'DOT_ID_Reporting_Airline', 'OP_CARRIER': 'IATA_CODE_Reporting_Airline', 'TAIL_NUM': 'Tail_Number', 'OP_CARRIER_FL_NUM': 'Flight_Number_Reporting_Airline', 'ORIGIN_AIRPORT_ID': 'OriginAirportID', \
    'ORIGIN_AIRPORT_SEQ_ID': 'OriginAirportSeqID', 'ORIGIN_CITY_MARKET_ID': 'OriginCityMarketID', 'ORIGIN': 'Origin', 'ORIGIN_CITY_NAME': 'OriginCityName', 'ORIGIN_STATE_ABR': 'OriginState', 'ORIGIN_STATE_FIPS': 'OriginStateFips', \
    'ORIGIN_STATE_NM': 'OriginStateName', 'ORIGIN_WAC': 'OriginWac', 'DEST_AIRPORT_ID': 'DestAirportID', 'DEST_AIRPORT_SEQ_ID': 'DestAirportSeqID', 'DEST_CITY_MARKET_ID': 'DestCityMarketID', 'DEST': 'Dest', 'DEST_CITY_NAME': 'DestCityName', \
    'DEST_STATE_ABR': 'DestState', 'DEST_STATE_FIPS': 'DestStateFips', 'DEST_STATE_NM': 'DestStateName', 'DEST_WAC': 'DestWac', 'CRS_DEP_TIME': 'CRSDepTime', 'DEP_TIME': 'DepTime', 'DEP_DELAY': 'DepDelay', 'DEP_DELAY_NEW': 'DepDelayMinutes', \
    'DEP_DEL15': 'DepDel15', 'DEP_DELAY_GROUP': 'DepartureDelayGroups', 'DEP_TIME_BLK': 'DepTimeBlk', 'TAXI_OUT': 'TaxiOut', 'WHEELS_OFF': 'WheelsOff', 'WHEELS_ON': 'WheelsOn', 'TAXI_IN': 'TaxiIn', 'CRS_ARR_TIME': 'CRSArrTime', 'ARR_TIME': 'ArrTime', \
    'ARR_DELAY': 'ArrDelay', 'ARR_DELAY_NEW': 'ArrDelayMinutes', 'ARR_DEL15': 'ArrDel15', 'ARR_DELAY_GROUP': 'ArrivalDelayGroups', 'ARR_TIME_BLK': 'ArrTimeBlk', 'CANCELLED': 'Cancelled', 'CANCELLATION_CODE': 'CancellationCode', 'DIVERTED': 'Diverted', \
    'CRS_ELAPSED_TIME': 'CRSElapsedTime', 'ACTUAL_ELAPSED_TIME': 'ActualElapsedTime', 'AIR_TIME': 'AirTime', 'FLIGHTS': 'Flights', 'DISTANCE': 'Distance', 'DISTANCE_GROUP': 'DistanceGroup', 'CARRIER_DELAY': 'CarrierDelay', 'WEATHER_DELAY': 'WeatherDelay', \
    'NAS_DELAY': 'NASDelay', 'SECURITY_DELAY': 'SecurityDelay', 'LATE_AIRCRAFT_DELAY': 'LateAircraftDelay', 'FIRST_DEP_TIME': 'FirstDepTime', 'TOTAL_ADD_GTIME': 'TotalAddGTime', 'LONGEST_ADD_GTIME': 'LongestAddGTime', 'DIV_AIRPORT_LANDINGS': 'DivAirportLandings', \
    'DIV_REACHED_DEST': 'DivReachedDest', 'DIV_ACTUAL_ELAPSED_TIME': 'DivActualElapsedTime', 'DIV_ARR_DELAY': 'DivArrDelay', 'DIV_DISTANCE': 'DivDistance', 'DIV1_AIRPORT': 'Div1Airport', 'DIV1_AIRPORT_ID': 'Div1AirportID', 'DIV1_AIRPORT_SEQ_ID': 'Div1AirportSeqID', \
    'DIV1_WHEELS_ON': 'Div1WheelsOn', 'DIV1_TOTAL_GTIME': 'Div1TotalGTime', 'DIV1_LONGEST_GTIME': 'Div1LongestGTime', 'DIV1_WHEELS_OFF': 'Div1WheelsOff', 'DIV1_TAIL_NUM': 'Div1TailNum', 'DIV2_AIRPORT': 'Div2Airport', 'DIV2_AIRPORT_ID': 'Div2AirportID', 'DIV2_AIRPORT_SEQ_ID': 'Div2AirportSeqID', \
    'DIV2_WHEELS_ON': 'Div2WheelsOn', 'DIV2_TOTAL_GTIME': 'Div2TotalGTime', 'DIV2_LONGEST_GTIME': 'Div2LongestGTime', 'DIV2_WHEELS_OFF': 'Div2WheelsOff', 'DIV2_TAIL_NUM': 'Div2TailNum', 'DIV3_AIRPORT': 'Div3Airport', 'DIV3_AIRPORT_ID': 'Div3AirportID', 'DIV3_AIRPORT_SEQ_ID': 'Div3AirportSeqID', \
    'DIV3_WHEELS_ON': 'Div3WheelsOn', 'DIV3_TOTAL_GTIME': 'Div3TotalGTime', 'DIV3_LONGEST_GTIME': 'Div3LongestGTime', 'DIV3_WHEELS_OFF': 'Div3WheelsOff', 'DIV3_TAIL_NUM': 'Div3TailNum', 'DIV4_AIRPORT': 'Div4Airport', 'DIV4_AIRPORT_ID': 'Div4AirportID', 'DIV4_AIRPORT_SEQ_ID': 'Div4AirportSeqID', \
    'DIV4_WHEELS_ON': 'Div4WheelsOn', 'DIV4_TOTAL_GTIME': 'Div4TotalGTime', 'DIV4_LONGEST_GTIME': 'Div4LongestGTime', 'DIV4_WHEELS_OFF': 'Div4WheelsOff', 'DIV4_TAIL_NUM': 'Div4TailNum', 'DIV5_AIRPORT': 'Div5Airport', 'DIV5_AIRPORT_ID': 'Div5AirportID', 'DIV5_AIRPORT_SEQ_ID': 'Div5AirportSeqID', \
    'DIV5_WHEELS_ON': 'Div5WheelsOn', 'DIV5_TOTAL_GTIME': 'Div5TotalGTime', 'DIV5_LONGEST_GTIME': 'Div5LongestGTime', 'DIV5_WHEELS_OFF': 'Div5WheelsOff', 'DIV5_TAIL_NUM': 'Div5TailNum'}, inplace=True)


combined_2019_df = pd.concat([df_jan2019, df_feb2019, df_mar2019, df_apr2019, df_may2019, df_june2019, df_july2019, df_aug2019, df_sep2019, df_oct2019, df_nov2019, df_dec2019])
combined_2019_df.drop(combined_2019_df.columns[combined_2019_df.columns.str.contains('Unnamed')], inplace=True, axis=1)

combined_2019_df.to_csv('/Users/jessicahalterman/Documents/MachineLearningProject/Data/2019.csv', index=False)